server:
  port: 9011

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/razorpay-merchant-db

jwt:
  secret-key: a9asd7fulasjdfaklsdfu98q3uhjdiosh897as9d8f7ua9osufdjilasdjf

webhoook:
  secret-encryption-key: jEbSy97ac+f1IDJCbVEMOZ4CJ2VzScYQljWrkxwyVWs=
